//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("qilive_dataModel", "fk_passenger_utid", "utid", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MTP.DAL.utid), "passenger", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MTP.DAL.passenger), true)]
[assembly: EdmRelationshipAttribute("qilive_dataModel", "fk_xml_booking_utid", "utid", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MTP.DAL.utid), "xml_booking", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MTP.DAL.xml_booking), true)]

#endregion

namespace MTP.DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class qilivedataEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new qilivedataEntities object using the connection string found in the 'qilivedataEntities' section of the application configuration file.
        /// </summary>
        public qilivedataEntities() : base("name=qilivedataEntities", "qilivedataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new qilivedataEntities object.
        /// </summary>
        public qilivedataEntities(string connectionString) : base(connectionString, "qilivedataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new qilivedataEntities object.
        /// </summary>
        public qilivedataEntities(EntityConnection connection) : base(connection, "qilivedataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<passenger> passengers
        {
            get
            {
                if ((_passengers == null))
                {
                    _passengers = base.CreateObjectSet<passenger>("passengers");
                }
                return _passengers;
            }
        }
        private ObjectSet<passenger> _passengers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<utid> utids
        {
            get
            {
                if ((_utids == null))
                {
                    _utids = base.CreateObjectSet<utid>("utids");
                }
                return _utids;
            }
        }
        private ObjectSet<utid> _utids;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<xml_booking> xml_booking
        {
            get
            {
                if ((_xml_booking == null))
                {
                    _xml_booking = base.CreateObjectSet<xml_booking>("xml_booking");
                }
                return _xml_booking;
            }
        }
        private ObjectSet<xml_booking> _xml_booking;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the passengers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopassengers(passenger passenger)
        {
            base.AddObject("passengers", passenger);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the utids EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToutids(utid utid)
        {
            base.AddObject("utids", utid);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the xml_booking EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToxml_booking(xml_booking xml_booking)
        {
            base.AddObject("xml_booking", xml_booking);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="p_RLOC">No Metadata Documentation available.</param>
        /// <param name="p_lastname">No Metadata Documentation available.</param>
        public ObjectResult<GetItineraryDataBySurnameAndRLOC_Result> GetItineraryDataBySurnameAndRLOC(global::System.String p_RLOC, global::System.String p_lastname)
        {
            ObjectParameter p_RLOCParameter;
            if (p_RLOC != null)
            {
                p_RLOCParameter = new ObjectParameter("p_RLOC", p_RLOC);
            }
            else
            {
                p_RLOCParameter = new ObjectParameter("p_RLOC", typeof(global::System.String));
            }
    
            ObjectParameter p_lastnameParameter;
            if (p_lastname != null)
            {
                p_lastnameParameter = new ObjectParameter("p_lastname", p_lastname);
            }
            else
            {
                p_lastnameParameter = new ObjectParameter("p_lastname", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<GetItineraryDataBySurnameAndRLOC_Result>("GetItineraryDataBySurnameAndRLOC", p_RLOCParameter, p_lastnameParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="email">No Metadata Documentation available.</param>
        public ObjectResult<GetBookingByEmail_Result> GetBookingByEmail(global::System.String email)
        {
            ObjectParameter emailParameter;
            if (email != null)
            {
                emailParameter = new ObjectParameter("email", email);
            }
            else
            {
                emailParameter = new ObjectParameter("email", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<GetBookingByEmail_Result>("GetBookingByEmail", emailParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="qilive_dataModel", Name="passenger")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class passenger : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new passenger object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="utid_id">Initial value of the utid_id property.</param>
        /// <param name="first_name">Initial value of the first_name property.</param>
        /// <param name="last_name">Initial value of the last_name property.</param>
        /// <param name="title">Initial value of the title property.</param>
        /// <param name="stamp">Initial value of the stamp property.</param>
        public static passenger Createpassenger(global::System.Int32 id, global::System.Int32 utid_id, global::System.String first_name, global::System.String last_name, global::System.String title, global::System.DateTime stamp)
        {
            passenger passenger = new passenger();
            passenger.id = id;
            passenger.utid_id = utid_id;
            passenger.first_name = first_name;
            passenger.last_name = last_name;
            passenger.title = title;
            passenger.stamp = stamp;
            return passenger;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 utid_id
        {
            get
            {
                return _utid_id;
            }
            set
            {
                Onutid_idChanging(value);
                ReportPropertyChanging("utid_id");
                _utid_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("utid_id");
                Onutid_idChanged();
            }
        }
        private global::System.Int32 _utid_id;
        partial void Onutid_idChanging(global::System.Int32 value);
        partial void Onutid_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String first_name
        {
            get
            {
                return _first_name;
            }
            set
            {
                Onfirst_nameChanging(value);
                ReportPropertyChanging("first_name");
                _first_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("first_name");
                Onfirst_nameChanged();
            }
        }
        private global::System.String _first_name;
        partial void Onfirst_nameChanging(global::System.String value);
        partial void Onfirst_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String last_name
        {
            get
            {
                return _last_name;
            }
            set
            {
                Onlast_nameChanging(value);
                ReportPropertyChanging("last_name");
                _last_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("last_name");
                Onlast_nameChanged();
            }
        }
        private global::System.String _last_name;
        partial void Onlast_nameChanging(global::System.String value);
        partial void Onlast_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime stamp
        {
            get
            {
                return _stamp;
            }
            set
            {
                OnstampChanging(value);
                ReportPropertyChanging("stamp");
                _stamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("stamp");
                OnstampChanged();
            }
        }
        private global::System.DateTime _stamp;
        partial void OnstampChanging(global::System.DateTime value);
        partial void OnstampChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("qilive_dataModel", "fk_passenger_utid", "utid")]
        public utid utid
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<utid>("qilive_dataModel.fk_passenger_utid", "utid").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<utid>("qilive_dataModel.fk_passenger_utid", "utid").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<utid> utidReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<utid>("qilive_dataModel.fk_passenger_utid", "utid");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<utid>("qilive_dataModel.fk_passenger_utid", "utid", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="qilive_dataModel", Name="utid")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class utid : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new utid object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="gds">Initial value of the gds property.</param>
        /// <param name="rLOC">Initial value of the RLOC property.</param>
        /// <param name="booking_date">Initial value of the booking_date property.</param>
        /// <param name="ubid">Initial value of the ubid property.</param>
        /// <param name="first_sighted">Initial value of the first_sighted property.</param>
        /// <param name="utid1">Initial value of the utid1 property.</param>
        /// <param name="status">Initial value of the status property.</param>
        /// <param name="source">Initial value of the source property.</param>
        /// <param name="stamp">Initial value of the stamp property.</param>
        public static utid Createutid(global::System.Int32 id, global::System.String gds, global::System.String rLOC, global::System.DateTime booking_date, global::System.String ubid, global::System.DateTime first_sighted, global::System.String utid1, global::System.String status, global::System.String source, global::System.DateTime stamp)
        {
            utid utid = new utid();
            utid.id = id;
            utid.gds = gds;
            utid.RLOC = rLOC;
            utid.booking_date = booking_date;
            utid.ubid = ubid;
            utid.first_sighted = first_sighted;
            utid.utid1 = utid1;
            utid.status = status;
            utid.source = source;
            utid.stamp = stamp;
            return utid;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String gds
        {
            get
            {
                return _gds;
            }
            set
            {
                OngdsChanging(value);
                ReportPropertyChanging("gds");
                _gds = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("gds");
                OngdsChanged();
            }
        }
        private global::System.String _gds;
        partial void OngdsChanging(global::System.String value);
        partial void OngdsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RLOC
        {
            get
            {
                return _RLOC;
            }
            set
            {
                OnRLOCChanging(value);
                ReportPropertyChanging("RLOC");
                _RLOC = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RLOC");
                OnRLOCChanged();
            }
        }
        private global::System.String _RLOC;
        partial void OnRLOCChanging(global::System.String value);
        partial void OnRLOCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime booking_date
        {
            get
            {
                return _booking_date;
            }
            set
            {
                Onbooking_dateChanging(value);
                ReportPropertyChanging("booking_date");
                _booking_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("booking_date");
                Onbooking_dateChanged();
            }
        }
        private global::System.DateTime _booking_date;
        partial void Onbooking_dateChanging(global::System.DateTime value);
        partial void Onbooking_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ubid
        {
            get
            {
                return _ubid;
            }
            set
            {
                OnubidChanging(value);
                ReportPropertyChanging("ubid");
                _ubid = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ubid");
                OnubidChanged();
            }
        }
        private global::System.String _ubid;
        partial void OnubidChanging(global::System.String value);
        partial void OnubidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime first_sighted
        {
            get
            {
                return _first_sighted;
            }
            set
            {
                Onfirst_sightedChanging(value);
                ReportPropertyChanging("first_sighted");
                _first_sighted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("first_sighted");
                Onfirst_sightedChanged();
            }
        }
        private global::System.DateTime _first_sighted;
        partial void Onfirst_sightedChanging(global::System.DateTime value);
        partial void Onfirst_sightedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String utid1
        {
            get
            {
                return _utid1;
            }
            set
            {
                Onutid1Changing(value);
                ReportPropertyChanging("utid1");
                _utid1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("utid1");
                Onutid1Changed();
            }
        }
        private global::System.String _utid1;
        partial void Onutid1Changing(global::System.String value);
        partial void Onutid1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.String _status;
        partial void OnstatusChanging(global::System.String value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String source
        {
            get
            {
                return _source;
            }
            set
            {
                OnsourceChanging(value);
                ReportPropertyChanging("source");
                _source = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("source");
                OnsourceChanged();
            }
        }
        private global::System.String _source;
        partial void OnsourceChanging(global::System.String value);
        partial void OnsourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime stamp
        {
            get
            {
                return _stamp;
            }
            set
            {
                OnstampChanging(value);
                ReportPropertyChanging("stamp");
                _stamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("stamp");
                OnstampChanged();
            }
        }
        private global::System.DateTime _stamp;
        partial void OnstampChanging(global::System.DateTime value);
        partial void OnstampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String region
        {
            get
            {
                return _region;
            }
            set
            {
                OnregionChanging(value);
                ReportPropertyChanging("region");
                _region = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("region");
                OnregionChanged();
            }
        }
        private global::System.String _region;
        partial void OnregionChanging(global::System.String value);
        partial void OnregionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String market
        {
            get
            {
                return _market;
            }
            set
            {
                OnmarketChanging(value);
                ReportPropertyChanging("market");
                _market = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("market");
                OnmarketChanged();
            }
        }
        private global::System.String _market;
        partial void OnmarketChanging(global::System.String value);
        partial void OnmarketChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String formname
        {
            get
            {
                return _formname;
            }
            set
            {
                OnformnameChanging(value);
                ReportPropertyChanging("formname");
                _formname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("formname");
                OnformnameChanged();
            }
        }
        private global::System.String _formname;
        partial void OnformnameChanging(global::System.String value);
        partial void OnformnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String company
        {
            get
            {
                return _company;
            }
            set
            {
                OncompanyChanging(value);
                ReportPropertyChanging("company");
                _company = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("company");
                OncompanyChanged();
            }
        }
        private global::System.String _company;
        partial void OncompanyChanging(global::System.String value);
        partial void OncompanyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String team
        {
            get
            {
                return _team;
            }
            set
            {
                OnteamChanging(value);
                ReportPropertyChanging("team");
                _team = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("team");
                OnteamChanged();
            }
        }
        private global::System.String _team;
        partial void OnteamChanging(global::System.String value);
        partial void OnteamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String notes
        {
            get
            {
                return _notes;
            }
            set
            {
                OnnotesChanging(value);
                ReportPropertyChanging("notes");
                _notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("notes");
                OnnotesChanged();
            }
        }
        private global::System.String _notes;
        partial void OnnotesChanging(global::System.String value);
        partial void OnnotesChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("qilive_dataModel", "fk_passenger_utid", "passenger")]
        public EntityCollection<passenger> passengers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<passenger>("qilive_dataModel.fk_passenger_utid", "passenger");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<passenger>("qilive_dataModel.fk_passenger_utid", "passenger", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("qilive_dataModel", "fk_xml_booking_utid", "xml_booking")]
        public EntityCollection<xml_booking> xml_booking
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<xml_booking>("qilive_dataModel.fk_xml_booking_utid", "xml_booking");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<xml_booking>("qilive_dataModel.fk_xml_booking_utid", "xml_booking", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="qilive_dataModel", Name="xml_booking")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class xml_booking : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new xml_booking object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="utid_id">Initial value of the utid_id property.</param>
        /// <param name="entry_date">Initial value of the entry_date property.</param>
        /// <param name="stamp">Initial value of the stamp property.</param>
        /// <param name="phase">Initial value of the phase property.</param>
        /// <param name="xml">Initial value of the xml property.</param>
        public static xml_booking Createxml_booking(global::System.Int32 id, global::System.Int32 utid_id, global::System.DateTime entry_date, global::System.DateTime stamp, global::System.String phase, global::System.String xml)
        {
            xml_booking xml_booking = new xml_booking();
            xml_booking.id = id;
            xml_booking.utid_id = utid_id;
            xml_booking.entry_date = entry_date;
            xml_booking.stamp = stamp;
            xml_booking.phase = phase;
            xml_booking.xml = xml;
            return xml_booking;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 utid_id
        {
            get
            {
                return _utid_id;
            }
            set
            {
                Onutid_idChanging(value);
                ReportPropertyChanging("utid_id");
                _utid_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("utid_id");
                Onutid_idChanged();
            }
        }
        private global::System.Int32 _utid_id;
        partial void Onutid_idChanging(global::System.Int32 value);
        partial void Onutid_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime entry_date
        {
            get
            {
                return _entry_date;
            }
            set
            {
                Onentry_dateChanging(value);
                ReportPropertyChanging("entry_date");
                _entry_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("entry_date");
                Onentry_dateChanged();
            }
        }
        private global::System.DateTime _entry_date;
        partial void Onentry_dateChanging(global::System.DateTime value);
        partial void Onentry_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime stamp
        {
            get
            {
                return _stamp;
            }
            set
            {
                OnstampChanging(value);
                ReportPropertyChanging("stamp");
                _stamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("stamp");
                OnstampChanged();
            }
        }
        private global::System.DateTime _stamp;
        partial void OnstampChanging(global::System.DateTime value);
        partial void OnstampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String phase
        {
            get
            {
                return _phase;
            }
            set
            {
                OnphaseChanging(value);
                ReportPropertyChanging("phase");
                _phase = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("phase");
                OnphaseChanged();
            }
        }
        private global::System.String _phase;
        partial void OnphaseChanging(global::System.String value);
        partial void OnphaseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String xml
        {
            get
            {
                return _xml;
            }
            set
            {
                OnxmlChanging(value);
                ReportPropertyChanging("xml");
                _xml = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("xml");
                OnxmlChanged();
            }
        }
        private global::System.String _xml;
        partial void OnxmlChanging(global::System.String value);
        partial void OnxmlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String notes
        {
            get
            {
                return _notes;
            }
            set
            {
                OnnotesChanging(value);
                ReportPropertyChanging("notes");
                _notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("notes");
                OnnotesChanged();
            }
        }
        private global::System.String _notes;
        partial void OnnotesChanging(global::System.String value);
        partial void OnnotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] pdf_file
        {
            get
            {
                return StructuralObject.GetValidValue(_pdf_file);
            }
            set
            {
                Onpdf_fileChanging(value);
                ReportPropertyChanging("pdf_file");
                _pdf_file = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pdf_file");
                Onpdf_fileChanged();
            }
        }
        private global::System.Byte[] _pdf_file;
        partial void Onpdf_fileChanging(global::System.Byte[] value);
        partial void Onpdf_fileChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("qilive_dataModel", "fk_xml_booking_utid", "utid")]
        public utid utid
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<utid>("qilive_dataModel.fk_xml_booking_utid", "utid").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<utid>("qilive_dataModel.fk_xml_booking_utid", "utid").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<utid> utidReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<utid>("qilive_dataModel.fk_xml_booking_utid", "utid");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<utid>("qilive_dataModel.fk_xml_booking_utid", "utid", value);
                }
            }
        }

        #endregion
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="qilive_dataModel", Name="ComplexType1")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class ComplexType1 : ComplexObject
    {
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="qilive_dataModel", Name="GetBookingByEmail_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class GetBookingByEmail_Result : ComplexObject
    {
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="qilive_dataModel", Name="GetItineraryDataBySurnameAndRLOC_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class GetItineraryDataBySurnameAndRLOC_Result : ComplexObject
    {
    }

    #endregion
    
}
