//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace MTP.DAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class qitransactionsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new qitransactionsEntities object using the connection string found in the 'qitransactionsEntities' section of the application configuration file.
        /// </summary>
        public qitransactionsEntities() : base("name=qitransactionsEntities", "qitransactionsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new qitransactionsEntities object.
        /// </summary>
        public qitransactionsEntities(string connectionString) : base(connectionString, "qitransactionsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new qitransactionsEntities object.
        /// </summary>
        public qitransactionsEntities(EntityConnection connection) : base(connection, "qitransactionsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<qicalevent> qicalevents
        {
            get
            {
                if ((_qicalevents == null))
                {
                    _qicalevents = base.CreateObjectSet<qicalevent>("qicalevents");
                }
                return _qicalevents;
            }
        }
        private ObjectSet<qicalevent> _qicalevents;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<qicalendar> qicalendars
        {
            get
            {
                if ((_qicalendars == null))
                {
                    _qicalendars = base.CreateObjectSet<qicalendar>("qicalendars");
                }
                return _qicalendars;
            }
        }
        private ObjectSet<qicalendar> _qicalendars;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<qimailrecord> qimailrecords
        {
            get
            {
                if ((_qimailrecords == null))
                {
                    _qimailrecords = base.CreateObjectSet<qimailrecord>("qimailrecords");
                }
                return _qimailrecords;
            }
        }
        private ObjectSet<qimailrecord> _qimailrecords;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the qicalevents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToqicalevents(qicalevent qicalevent)
        {
            base.AddObject("qicalevents", qicalevent);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the qicalendars EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToqicalendars(qicalendar qicalendar)
        {
            base.AddObject("qicalendars", qicalendar);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the qimailrecords EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToqimailrecords(qimailrecord qimailrecord)
        {
            base.AddObject("qimailrecords", qimailrecord);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="qitransactionsModel", Name="qicalendar")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class qicalendar : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new qicalendar object.
        /// </summary>
        /// <param name="gDS">Initial value of the GDS property.</param>
        /// <param name="rLoc">Initial value of the RLoc property.</param>
        /// <param name="stamp">Initial value of the Stamp property.</param>
        public static qicalendar Createqicalendar(global::System.String gDS, global::System.String rLoc, global::System.DateTime stamp)
        {
            qicalendar qicalendar = new qicalendar();
            qicalendar.GDS = gDS;
            qicalendar.RLoc = rLoc;
            qicalendar.Stamp = stamp;
            return qicalendar;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GDS
        {
            get
            {
                return _GDS;
            }
            set
            {
                if (_GDS != value)
                {
                    OnGDSChanging(value);
                    ReportPropertyChanging("GDS");
                    _GDS = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("GDS");
                    OnGDSChanged();
                }
            }
        }
        private global::System.String _GDS;
        partial void OnGDSChanging(global::System.String value);
        partial void OnGDSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RLoc
        {
            get
            {
                return _RLoc;
            }
            set
            {
                if (_RLoc != value)
                {
                    OnRLocChanging(value);
                    ReportPropertyChanging("RLoc");
                    _RLoc = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("RLoc");
                    OnRLocChanged();
                }
            }
        }
        private global::System.String _RLoc;
        partial void OnRLocChanging(global::System.String value);
        partial void OnRLocChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PaxName
        {
            get
            {
                return _PaxName;
            }
            set
            {
                OnPaxNameChanging(value);
                ReportPropertyChanging("PaxName");
                _PaxName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PaxName");
                OnPaxNameChanged();
            }
        }
        private global::System.String _PaxName;
        partial void OnPaxNameChanging(global::System.String value);
        partial void OnPaxNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Language
        {
            get
            {
                return _Language;
            }
            set
            {
                OnLanguageChanging(value);
                ReportPropertyChanging("Language");
                _Language = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Language");
                OnLanguageChanged();
            }
        }
        private global::System.String _Language;
        partial void OnLanguageChanging(global::System.String value);
        partial void OnLanguageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FileLocation
        {
            get
            {
                return _FileLocation;
            }
            set
            {
                OnFileLocationChanging(value);
                ReportPropertyChanging("FileLocation");
                _FileLocation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FileLocation");
                OnFileLocationChanged();
            }
        }
        private global::System.String _FileLocation;
        partial void OnFileLocationChanging(global::System.String value);
        partial void OnFileLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Stamp
        {
            get
            {
                return _Stamp;
            }
            set
            {
                OnStampChanging(value);
                ReportPropertyChanging("Stamp");
                _Stamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Stamp");
                OnStampChanged();
            }
        }
        private global::System.DateTime _Stamp;
        partial void OnStampChanging(global::System.DateTime value);
        partial void OnStampChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="qitransactionsModel", Name="qicalevent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class qicalevent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new qicalevent object.
        /// </summary>
        /// <param name="gDS">Initial value of the GDS property.</param>
        /// <param name="rLOC">Initial value of the RLOC property.</param>
        /// <param name="paxName">Initial value of the PaxName property.</param>
        /// <param name="segNumber">Initial value of the SegNumber property.</param>
        public static qicalevent Createqicalevent(global::System.String gDS, global::System.String rLOC, global::System.String paxName, global::System.Int32 segNumber)
        {
            qicalevent qicalevent = new qicalevent();
            qicalevent.GDS = gDS;
            qicalevent.RLOC = rLOC;
            qicalevent.PaxName = paxName;
            qicalevent.SegNumber = segNumber;
            return qicalevent;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GDS
        {
            get
            {
                return _GDS;
            }
            set
            {
                if (_GDS != value)
                {
                    OnGDSChanging(value);
                    ReportPropertyChanging("GDS");
                    _GDS = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("GDS");
                    OnGDSChanged();
                }
            }
        }
        private global::System.String _GDS;
        partial void OnGDSChanging(global::System.String value);
        partial void OnGDSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RLOC
        {
            get
            {
                return _RLOC;
            }
            set
            {
                if (_RLOC != value)
                {
                    OnRLOCChanging(value);
                    ReportPropertyChanging("RLOC");
                    _RLOC = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("RLOC");
                    OnRLOCChanged();
                }
            }
        }
        private global::System.String _RLOC;
        partial void OnRLOCChanging(global::System.String value);
        partial void OnRLOCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PaxName
        {
            get
            {
                return _PaxName;
            }
            set
            {
                if (_PaxName != value)
                {
                    OnPaxNameChanging(value);
                    ReportPropertyChanging("PaxName");
                    _PaxName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PaxName");
                    OnPaxNameChanged();
                }
            }
        }
        private global::System.String _PaxName;
        partial void OnPaxNameChanging(global::System.String value);
        partial void OnPaxNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SegNumber
        {
            get
            {
                return _SegNumber;
            }
            set
            {
                if (_SegNumber != value)
                {
                    OnSegNumberChanging(value);
                    ReportPropertyChanging("SegNumber");
                    _SegNumber = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SegNumber");
                    OnSegNumberChanged();
                }
            }
        }
        private global::System.Int32 _SegNumber;
        partial void OnSegNumberChanging(global::System.Int32 value);
        partial void OnSegNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SegType
        {
            get
            {
                return _SegType;
            }
            set
            {
                OnSegTypeChanging(value);
                ReportPropertyChanging("SegType");
                _SegType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SegType");
                OnSegTypeChanged();
            }
        }
        private global::System.String _SegType;
        partial void OnSegTypeChanging(global::System.String value);
        partial void OnSegTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DTStart
        {
            get
            {
                return _DTStart;
            }
            set
            {
                OnDTStartChanging(value);
                ReportPropertyChanging("DTStart");
                _DTStart = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DTStart");
                OnDTStartChanged();
            }
        }
        private global::System.String _DTStart;
        partial void OnDTStartChanging(global::System.String value);
        partial void OnDTStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DTEnd
        {
            get
            {
                return _DTEnd;
            }
            set
            {
                OnDTEndChanging(value);
                ReportPropertyChanging("DTEnd");
                _DTEnd = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DTEnd");
                OnDTEndChanged();
            }
        }
        private global::System.String _DTEnd;
        partial void OnDTEndChanging(global::System.String value);
        partial void OnDTEndChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DCreated
        {
            get
            {
                return _DCreated;
            }
            set
            {
                OnDCreatedChanging(value);
                ReportPropertyChanging("DCreated");
                _DCreated = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DCreated");
                OnDCreatedChanged();
            }
        }
        private global::System.String _DCreated;
        partial void OnDCreatedChanging(global::System.String value);
        partial void OnDCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UID
        {
            get
            {
                return _UID;
            }
            set
            {
                OnUIDChanging(value);
                ReportPropertyChanging("UID");
                _UID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UID");
                OnUIDChanged();
            }
        }
        private global::System.String _UID;
        partial void OnUIDChanging(global::System.String value);
        partial void OnUIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Subject
        {
            get
            {
                return _Subject;
            }
            set
            {
                OnSubjectChanging(value);
                ReportPropertyChanging("Subject");
                _Subject = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Subject");
                OnSubjectChanged();
            }
        }
        private global::System.String _Subject;
        partial void OnSubjectChanging(global::System.String value);
        partial void OnSubjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AltDescription
        {
            get
            {
                return _AltDescription;
            }
            set
            {
                OnAltDescriptionChanging(value);
                ReportPropertyChanging("AltDescription");
                _AltDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AltDescription");
                OnAltDescriptionChanged();
            }
        }
        private global::System.String _AltDescription;
        partial void OnAltDescriptionChanging(global::System.String value);
        partial void OnAltDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EventText
        {
            get
            {
                return _EventText;
            }
            set
            {
                OnEventTextChanging(value);
                ReportPropertyChanging("EventText");
                _EventText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EventText");
                OnEventTextChanged();
            }
        }
        private global::System.String _EventText;
        partial void OnEventTextChanging(global::System.String value);
        partial void OnEventTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Stamp
        {
            get
            {
                return _Stamp;
            }
            set
            {
                OnStampChanging(value);
                ReportPropertyChanging("Stamp");
                _Stamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Stamp");
                OnStampChanged();
            }
        }
        private Nullable<global::System.DateTime> _Stamp;
        partial void OnStampChanging(Nullable<global::System.DateTime> value);
        partial void OnStampChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="qitransactionsModel", Name="qimailrecord")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class qimailrecord : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new qimailrecord object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="processed">Initial value of the Processed property.</param>
        /// <param name="itinType">Initial value of the ItinType property.</param>
        /// <param name="time_stamp">Initial value of the time_stamp property.</param>
        /// <param name="pseudo">Initial value of the Pseudo property.</param>
        public static qimailrecord Createqimailrecord(global::System.Int32 id, global::System.Int32 processed, global::System.Int32 itinType, global::System.DateTime time_stamp, global::System.String pseudo)
        {
            qimailrecord qimailrecord = new qimailrecord();
            qimailrecord.ID = id;
            qimailrecord.Processed = processed;
            qimailrecord.ItinType = itinType;
            qimailrecord.time_stamp = time_stamp;
            qimailrecord.Pseudo = pseudo;
            return qimailrecord;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RLOC
        {
            get
            {
                return _RLOC;
            }
            set
            {
                OnRLOCChanging(value);
                ReportPropertyChanging("RLOC");
                _RLOC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RLOC");
                OnRLOCChanged();
            }
        }
        private global::System.String _RLOC;
        partial void OnRLOCChanging(global::System.String value);
        partial void OnRLOCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Subject
        {
            get
            {
                return _Subject;
            }
            set
            {
                OnSubjectChanging(value);
                ReportPropertyChanging("Subject");
                _Subject = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Subject");
                OnSubjectChanged();
            }
        }
        private global::System.String _Subject;
        partial void OnSubjectChanging(global::System.String value);
        partial void OnSubjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FromName
        {
            get
            {
                return _FromName;
            }
            set
            {
                OnFromNameChanging(value);
                ReportPropertyChanging("FromName");
                _FromName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FromName");
                OnFromNameChanged();
            }
        }
        private global::System.String _FromName;
        partial void OnFromNameChanging(global::System.String value);
        partial void OnFromNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SenderName
        {
            get
            {
                return _SenderName;
            }
            set
            {
                OnSenderNameChanging(value);
                ReportPropertyChanging("SenderName");
                _SenderName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SenderName");
                OnSenderNameChanged();
            }
        }
        private global::System.String _SenderName;
        partial void OnSenderNameChanging(global::System.String value);
        partial void OnSenderNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ToName
        {
            get
            {
                return _ToName;
            }
            set
            {
                OnToNameChanging(value);
                ReportPropertyChanging("ToName");
                _ToName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ToName");
                OnToNameChanged();
            }
        }
        private global::System.String _ToName;
        partial void OnToNameChanging(global::System.String value);
        partial void OnToNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Received
        {
            get
            {
                return _Received;
            }
            set
            {
                OnReceivedChanging(value);
                ReportPropertyChanging("Received");
                _Received = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Received");
                OnReceivedChanged();
            }
        }
        private Nullable<global::System.DateTime> _Received;
        partial void OnReceivedChanging(Nullable<global::System.DateTime> value);
        partial void OnReceivedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DeliveryTime
        {
            get
            {
                return _DeliveryTime;
            }
            set
            {
                OnDeliveryTimeChanging(value);
                ReportPropertyChanging("DeliveryTime");
                _DeliveryTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DeliveryTime");
                OnDeliveryTimeChanged();
            }
        }
        private global::System.String _DeliveryTime;
        partial void OnDeliveryTimeChanging(global::System.String value);
        partial void OnDeliveryTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Contents
        {
            get
            {
                return _Contents;
            }
            set
            {
                OnContentsChanging(value);
                ReportPropertyChanging("Contents");
                _Contents = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Contents");
                OnContentsChanged();
            }
        }
        private global::System.String _Contents;
        partial void OnContentsChanging(global::System.String value);
        partial void OnContentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Agent
        {
            get
            {
                return _Agent;
            }
            set
            {
                OnAgentChanging(value);
                ReportPropertyChanging("Agent");
                _Agent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Agent");
                OnAgentChanged();
            }
        }
        private global::System.String _Agent;
        partial void OnAgentChanging(global::System.String value);
        partial void OnAgentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Method
        {
            get
            {
                return _Method;
            }
            set
            {
                OnMethodChanging(value);
                ReportPropertyChanging("Method");
                _Method = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Method");
                OnMethodChanged();
            }
        }
        private global::System.String _Method;
        partial void OnMethodChanging(global::System.String value);
        partial void OnMethodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Processor
        {
            get
            {
                return _Processor;
            }
            set
            {
                OnProcessorChanging(value);
                ReportPropertyChanging("Processor");
                _Processor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Processor");
                OnProcessorChanged();
            }
        }
        private Nullable<global::System.Int32> _Processor;
        partial void OnProcessorChanging(Nullable<global::System.Int32> value);
        partial void OnProcessorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProcessorName
        {
            get
            {
                return _ProcessorName;
            }
            set
            {
                OnProcessorNameChanging(value);
                ReportPropertyChanging("ProcessorName");
                _ProcessorName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProcessorName");
                OnProcessorNameChanged();
            }
        }
        private global::System.String _ProcessorName;
        partial void OnProcessorNameChanging(global::System.String value);
        partial void OnProcessorNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FormName
        {
            get
            {
                return _FormName;
            }
            set
            {
                OnFormNameChanging(value);
                ReportPropertyChanging("FormName");
                _FormName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FormName");
                OnFormNameChanged();
            }
        }
        private global::System.String _FormName;
        partial void OnFormNameChanging(global::System.String value);
        partial void OnFormNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _Created;
        partial void OnCreatedChanging(Nullable<global::System.DateTime> value);
        partial void OnCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PreprocStatus
        {
            get
            {
                return _PreprocStatus;
            }
            set
            {
                OnPreprocStatusChanging(value);
                ReportPropertyChanging("PreprocStatus");
                _PreprocStatus = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PreprocStatus");
                OnPreprocStatusChanged();
            }
        }
        private Nullable<global::System.Int32> _PreprocStatus;
        partial void OnPreprocStatusChanging(Nullable<global::System.Int32> value);
        partial void OnPreprocStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TicketNumber
        {
            get
            {
                return _TicketNumber;
            }
            set
            {
                OnTicketNumberChanging(value);
                ReportPropertyChanging("TicketNumber");
                _TicketNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TicketNumber");
                OnTicketNumberChanged();
            }
        }
        private global::System.String _TicketNumber;
        partial void OnTicketNumberChanging(global::System.String value);
        partial void OnTicketNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DocumentNumber
        {
            get
            {
                return _DocumentNumber;
            }
            set
            {
                OnDocumentNumberChanging(value);
                ReportPropertyChanging("DocumentNumber");
                _DocumentNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DocumentNumber");
                OnDocumentNumberChanged();
            }
        }
        private global::System.String _DocumentNumber;
        partial void OnDocumentNumberChanging(global::System.String value);
        partial void OnDocumentNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OrderNumber
        {
            get
            {
                return _OrderNumber;
            }
            set
            {
                OnOrderNumberChanging(value);
                ReportPropertyChanging("OrderNumber");
                _OrderNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OrderNumber");
                OnOrderNumberChanged();
            }
        }
        private global::System.String _OrderNumber;
        partial void OnOrderNumberChanging(global::System.String value);
        partial void OnOrderNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomerReference
        {
            get
            {
                return _CustomerReference;
            }
            set
            {
                OnCustomerReferenceChanging(value);
                ReportPropertyChanging("CustomerReference");
                _CustomerReference = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustomerReference");
                OnCustomerReferenceChanged();
            }
        }
        private global::System.String _CustomerReference;
        partial void OnCustomerReferenceChanging(global::System.String value);
        partial void OnCustomerReferenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Processed
        {
            get
            {
                return _Processed;
            }
            set
            {
                OnProcessedChanging(value);
                ReportPropertyChanging("Processed");
                _Processed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Processed");
                OnProcessedChanged();
            }
        }
        private global::System.Int32 _Processed;
        partial void OnProcessedChanging(global::System.Int32 value);
        partial void OnProcessedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Company
        {
            get
            {
                return _Company;
            }
            set
            {
                OnCompanyChanging(value);
                ReportPropertyChanging("Company");
                _Company = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Company");
                OnCompanyChanged();
            }
        }
        private global::System.String _Company;
        partial void OnCompanyChanging(global::System.String value);
        partial void OnCompanyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Category
        {
            get
            {
                return _Category;
            }
            set
            {
                OnCategoryChanging(value);
                ReportPropertyChanging("Category");
                _Category = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Category");
                OnCategoryChanged();
            }
        }
        private global::System.String _Category;
        partial void OnCategoryChanging(global::System.String value);
        partial void OnCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ItinType
        {
            get
            {
                return _ItinType;
            }
            set
            {
                OnItinTypeChanging(value);
                ReportPropertyChanging("ItinType");
                _ItinType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ItinType");
                OnItinTypeChanged();
            }
        }
        private global::System.Int32 _ItinType;
        partial void OnItinTypeChanging(global::System.Int32 value);
        partial void OnItinTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime time_stamp
        {
            get
            {
                return _time_stamp;
            }
            set
            {
                Ontime_stampChanging(value);
                ReportPropertyChanging("time_stamp");
                _time_stamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("time_stamp");
                Ontime_stampChanged();
            }
        }
        private global::System.DateTime _time_stamp;
        partial void Ontime_stampChanging(global::System.DateTime value);
        partial void Ontime_stampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TripRequest
        {
            get
            {
                return _TripRequest;
            }
            set
            {
                OnTripRequestChanging(value);
                ReportPropertyChanging("TripRequest");
                _TripRequest = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TripRequest");
                OnTripRequestChanged();
            }
        }
        private global::System.String _TripRequest;
        partial void OnTripRequestChanging(global::System.String value);
        partial void OnTripRequestChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Pseudo
        {
            get
            {
                return _Pseudo;
            }
            set
            {
                OnPseudoChanging(value);
                ReportPropertyChanging("Pseudo");
                _Pseudo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Pseudo");
                OnPseudoChanged();
            }
        }
        private global::System.String _Pseudo;
        partial void OnPseudoChanging(global::System.String value);
        partial void OnPseudoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Team
        {
            get
            {
                return _Team;
            }
            set
            {
                OnTeamChanging(value);
                ReportPropertyChanging("Team");
                _Team = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Team");
                OnTeamChanged();
            }
        }
        private global::System.String _Team;
        partial void OnTeamChanging(global::System.String value);
        partial void OnTeamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BounceEmailId
        {
            get
            {
                return _BounceEmailId;
            }
            set
            {
                OnBounceEmailIdChanging(value);
                ReportPropertyChanging("BounceEmailId");
                _BounceEmailId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BounceEmailId");
                OnBounceEmailIdChanged();
            }
        }
        private Nullable<global::System.Int32> _BounceEmailId;
        partial void OnBounceEmailIdChanging(Nullable<global::System.Int32> value);
        partial void OnBounceEmailIdChanged();

        #endregion
    
    }

    #endregion
    
}
